// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBd_oxAo7NSdpMymI5R4DX-rDG3itYvEc',
    appId: '1:981164511645:web:5d698bc2eea547b8c75f74',
    messagingSenderId: '981164511645',
    projectId: 'wireless-project-359b9',
    authDomain: 'wireless-project-359b9.firebaseapp.com',
    storageBucket: 'wireless-project-359b9.appspot.com',
    measurementId: 'G-SXPZNRNJLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQD9rCJg6KeSusfqNEjs6m16eTjuOmiEk',
    appId: '1:981164511645:android:e0d207b7b2df1f8cc75f74',
    messagingSenderId: '981164511645',
    projectId: 'wireless-project-359b9',
    storageBucket: 'wireless-project-359b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQW2723MYczT9UZ6gdeZd4oHBukrllyT0',
    appId: '1:981164511645:ios:f150c98a280e71e4c75f74',
    messagingSenderId: '981164511645',
    projectId: 'wireless-project-359b9',
    storageBucket: 'wireless-project-359b9.appspot.com',
    iosBundleId: 'com.example.googleMapsYt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQW2723MYczT9UZ6gdeZd4oHBukrllyT0',
    appId: '1:981164511645:ios:3a6aa0fcac50ea23c75f74',
    messagingSenderId: '981164511645',
    projectId: 'wireless-project-359b9',
    storageBucket: 'wireless-project-359b9.appspot.com',
    iosBundleId: 'com.example.googleMapsYt.RunnerTests',
  );
}
